# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
  pull_request:

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Air
        uses: posit-dev/setup-air@v1

      - name: Check
        run: air format . --check
